### ISSUE TITLE
Custom EDID, faild to work on Ubuntu 16.04.5

### ISSUE THREAD

**Issue by bademux** [akatrevorjay/edid-generator#14]
First of all tanks for nice tool, it seems to be the only way to set custom EDID when using wayland.
Unfortunatly I have a problem with custom Modeline generated with [cvt_modeline_calculator_12](https://github.com/kevinlekiller/cvt_modeline_calculator_12).
Modeline generated with ``` cvt12 3840 2160 26 -b ```
Using ```xrandr --newmode``` 3840x2160_26.00_rb2 works great , but I got error during boot when using EDID as firmware:
```
platform HDMI-A-2: Direct firmware load for edid/3840x2160_26.00_rb2.bin failed with error -2
[drm:drm_load_edid_firmware [drm]] *ERROR* Requesting EDID firmware "edid/3840x2160_26.00_rb2.bin" failed (err=-2)
```
_cat 3840x2160_26.00_rb2.S_
```c
/* 3840x2160_26.00_rb2: Modeline "3840x2160_26.00_rb2" 222.90 3840 3848 3880 3920 2160 2173 2181 2187 +hsync -vsync */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+8)
#define XPULSE 32
#define YPIX 2160
#define XPIX 3840
#define VFREQ 60
#define DPI 96
#define CLOCK 222900
#define VERSION 1
#define REVISION 3
#define XOFFSET 8
#define YOFFSET (63+13)
#define XY_RATIO XY_RATIO_16_9
#define YBLANK 27
#define XBLANK 80
#define TIMING_NAME "3840x2160_26.00_rb2"
#include "edid.S"
```

**Comment by aqxa1** [comment]
For some reason, if the modeline name is longer than a certain amount of characters, it completely breaks the edid. You can verify this with edid-decode or parse-edid, where you'll see that checksum is invalid and there are additional extension blocks (proportional to how long the modeline name is). It also looks like the name of the monitor is set to the name of the modeline, which I'm not sure is ideal (and may be related).

Anyway, as a workaround, you can shorten the length of the modeline to something like "3840x2160". I've found that 12 characters is the limit, so you could also use "3840x2160_26", but no longer.

Examples to show the problem:
With modeline set to "2560x1440_xx":
`
EDID version: 1.3                                                                                                                                                                                                                                             
Manufacturer: LNX Model 0 Serial Number 0
Made in week 5 of 2012
Analog display, Input voltage level: 0.7/0.7 V
Sync: Separate Composite Serration 
Maximum image size: 66 cm x 37 cm
Gamma: 2.20
DPMS levels: Standby Suspend Off
RGB color display
First detailed timing is preferred timing
Display x,y Chromaticity:
  Red:   0.6416, 0.3486
  Green: 0.2919, 0.5957
  Blue:  0.1474, 0.1250
  White: 0.3125, 0.3281
Established timings supported:
Standard timings supported:
  512x288@60Hz 16:9
Detailed mode: Clock 409.090 MHz, 666 mm x 375 mm
               2560 2608 2640 2720 hborder 0
               1440 1447 1452 1504 vborder 0
               +hsync +vsync 
               VertFreq: 100 Hz, HorFreq: 150400 Hz
Serial number: Linux #0
Monitor ranges (GTF): 59-61Hz V, 149-151kHz H, max dotclock 410MHz
Monitor name: 2560x1440_xx
**Checksum: 0xdf (valid)**

    EDID version: 1.3                                                                                                                                                                                                                                             
Manufacturer: LNX Model 0 Serial Number 0
Made in week 5 of 2012
Analog display, Input voltage level: 0.7/0.7 V
Sync: Separate Composite Serration 
Maximum image size: 66 cm x 37 cm
Gamma: 2.20
DPMS levels: Standby Suspend Off
RGB color display
First detailed timing is preferred timing
Display x,y Chromaticity:
  Red:   0.6416, 0.3486
  Green: 0.2919, 0.5957
  Blue:  0.1474, 0.1250
  White: 0.3125, 0.3281
Established timings supported:
Standard timings supported:
  512x288@60Hz 16:9
Detailed mode: Clock 409.090 MHz, 666 mm x 375 mm
               2560 2608 2640 2720 hborder 0
               1440 1447 1452 1504 vborder 0
               +hsync +vsync 
               VertFreq: 100 Hz, HorFreq: 150400 Hz
Serial number: Linux #0
Monitor ranges (GTF): 59-61Hz V, 149-151kHz H, max dotclock 410MHz
Monitor name: 2560x1440
Checksum: 0xce (valid)
`

With modeline name set to "2560x1440_xxx":
`
EDID version: 1.3                                                                                                                                                                                                                                             
Manufacturer: LNX Model 0 Serial Number 0
Made in week 5 of 2012
Analog display, Input voltage level: 0.7/0.7 V
Sync: Separate Composite Serration 
Maximum image size: 66 cm x 37 cm
Gamma: 2.20
DPMS levels: Standby Suspend Off
RGB color display
First detailed timing is preferred timing
Display x,y Chromaticity:
  Red:   0.6416, 0.3486
  Green: 0.2919, 0.5957
  Blue:  0.1474, 0.1250
  White: 0.3125, 0.3281
Established timings supported:
Standard timings supported:
  512x288@60Hz 16:9
Detailed mode: Clock 409.090 MHz, 666 mm x 375 mm
               2560 2608 2640 2720 hborder 0
               1440 1447 1452 1504 vborder 0
               +hsync +vsync 
               VertFreq: 100 Hz, HorFreq: 150400 Hz
Serial number: Linux #0
Monitor ranges (GTF): 59-61Hz V, 149-151kHz H, max dotclock 410MHz
Monitor name: 2560x1440_xxx
**Has 10 extension blocks**
**Checksum: 0x0 (should be 0x67)**
`

As you can see, with the longer modeline name, there are additional checksum blocks, and the checksum is invalid.
