### ISSUE TITLE
Can these be burned to serial ROM as is?

### ISSUE THREAD

**Issue by aarcane** [akatrevorjay/edid-generator#6]
I have a project that's using a monitor.  The monitor we sourced doesn't include an EDID image, but adding one inline using a serial EEPROM would be possible.  We just need to be able to generate an EDID Firmware to make it work.

**Comment by akatrevorjay** [comment]
Hi, it worked for me on my TV, but I don't know anything about your device in particular, so YMMV don't trust me ;)

**Comment by akatrevorjay** [comment]
(feel free to reopen if anything else comes to mind, or make a new one, up to you)
